/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d8e3fb",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "error": "#ba1a1a",
        "surface-tint": "#3a5f94",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#1f477b",
        "surface-dim": "#cfdaf2",
        "outline-variant": "#c3c6d1",
        "surface-container": "#e7eeff",
        "on-primary-container": "#799dd6",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-low": "#f0f3ff",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
        "on-surface": "#111c2d",
        "primary-fixed": "#d5e3ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#111c2d",
        "primary-container": "#003366",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary-container": "#8c9cb5",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary-container": "#243448",
        "outline": "#737780",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed-variant": "#454747",
        "background": "#f9f9ff",
        "surface-variant": "#d8e3fb",
        "surface-bright": "#f9f9ff",
        "tertiary": "#0e1f32",
        "on-error-container": "#93000a",
        "inverse-primary": "#a7c8ff",
        "primary": "#001e40",
        "surface": "#f9f9ff",
        "tertiary-fixed": "#d3e4fe",
        "on-secondary-container": "#5f6161",
        "inverse-surface": "#263143",
        "on-surface-variant": "#43474f",
        "secondary-container": "#dcdddd",
        "secondary": "#5d5f5f",
        "surface-container-high": "#dee8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "card-gap": "1rem",
        "gutter": "1.5rem",
        "container-padding-desktop": "4rem",
        "section-gap": "5rem",
        "container-padding-mobile": "1.25rem"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["Public Sans"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Public Sans"],
        "body-lg": ["Public Sans"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
